name: bilibili-daily-task


on:

  push: # push触发
    branches: [ main ]
  workflow_dispatch: # 手动触发


jobs:
  run-go:
    run-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.1'

    - run: go version
    # 运行
    - name: Run
      env:
        development: ${secrets.development}
      run: go run hello.go -development=${development}
